[env]
TERM = "xterm-256color"

[font]
size = 16
normal = { family = "GoogleSansCode Nerd Font Mono", style = "Light" }
bold = { family = "GoogleSansCode Nerd Font Mono", style = "Regular" }
italic = { family = "GoogleSansCode Nerd Font Mono", style = "Light Italic" }
bold_italic = { family = "GoogleSansCode Nerd Font Mono", style = "Italic" }
offset = { y = 16 }
glyph_offset = { y = 8 }

[window]
dynamic_padding = true
decorations = "Buttonless"
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/theme.toml"
]

[[keyboard.bindings]]
# Add support for line breaks with shift+enter in Claude Code
key = "Return"
mods = "Shift"
chars = "\u001B\r"
