#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking Alacritty configuration..."
ALACRITTY_DIR="$HOME/.config/alacritty"
rm -rf "$ALACRITTY_DIR"
ln -s "$DOTFILES_DIR/alacritty" "$ALACRITTY_DIR"
