#!/usr/bin/env bash

DOTFILESDIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking kitty configuration..."
KITTY_DIR="$HOME/.config/kitty"
rm -rf "$KITTY_DIR"
ln -s "$DOTFILESDIR/kitty" "$KITTY_DIR"

echo "Linking tmux configuration..."
TMUX_DIR="$HOME/.tmux.conf"
rm -rf "$TMUX_DIR"
ln -s "$DOTFILESDIR/tmux/tmux.conf" "$TMUX_DIR"

echo "Linking nvim configuration..."
NVIM_DIR="$HOME/.config/nvim"
rm -rf "$NVIM_DIR"
ln -s "$DOTFILESDIR/nvim" "$NVIM_DIR"

echo "Linking lazygit configuration..."
LAZYGIT_DIR="$HOME/Library/Application Support/lazygit"
rm -rf "$LAZYGIT_DIR"
ln -s "$DOTFILESDIR/lazygit" "$LAZYGIT_DIR"

echo "Linking wezterm configuration..."
WEZTERM_DIR="$HOME/.config/wezterm"
rm -rf "$WEZTERM_DIR"
ln -s "$DOTFILESDIR/wezterm" "$WEZTERM_DIR"
