#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking tmux configuration..."
TMUX_FILE="$HOME/.tmux.conf"
rm -f "$TMUX_FILE"
ln -s "$DOTFILES_DIR/tmux/tmux.conf" "$TMUX_FILE"
