#!/usr/bin/env bash

DOTFILESDIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking WezTerm configuration..."
WEZTERM_DIR="$HOME/.config/wezterm"
rm -rf "$WEZTERM_DIR"
ln -s "$DOTFILESDIR/wezterm" "$WEZTERM_DIR"
