#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking WezTerm configuration..."
WEZTERM_DIR="$HOME/.config/wezterm"
rm -rf "$WEZTERM_DIR"
ln -s "$DOTFILES_DIR/wezterm" "$WEZTERM_DIR"
