#!/usr/bin/env bash

DOTFILESDIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking LazyGit configuration..."
LAZYGIT_DIR="$HOME/Library/Application Support/lazygit"
rm -rf "$LAZYGIT_DIR"
ln -s "$DOTFILESDIR/lazygit" "$LAZYGIT_DIR"
