#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking LazyGit configuration..."
LAZYGIT_DIR="$HOME/Library/Application Support/lazygit"
rm -rf "$LAZYGIT_DIR"
ln -s "$DOTFILES_DIR/lazygit" "$LAZYGIT_DIR"
