#!/usr/bin/env bash

DOTFILESDIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Linking Ghostty configuration..."
GHOSTTY_DIR="$HOME/.config/ghostty"
rm -rf "$GHOSTTY_DIR"
ln -s "$DOTFILESDIR/ghostty" "$GHOSTTY_DIR"
