#!/usr/bin/env bash

USER_ID=$(id -u ${USER})
GROUP_ID=$(id -g ${USER})

echo "Building Maverick Docker for user ${USER_ID}:${GROUP_ID} ..."
docker build --build-arg USER_ID=${USER_ID} --build-arg GROUP_ID=${GROUP_ID} -t maverick .
